#!/usr/bin/env bash
# audit/cleanup.sh — generated by the Zero-Touch audit (2026-08-09), STATE 5.
#
# NOT executed by the audit loop. Run this yourself, at your convenience, from
# the repo root, on a clean working tree. Each step is guarded: it re-checks
# its own precondition before touching anything, and prints what it's about
# to do before doing it. Nothing here force-pushes, deletes branches, or
# touches main directly — those are flagged as manual steps instead.
#
# IMPORTANT — CSS selector removal discipline (per tools/dev/README.md's own
# rule): "Cutting rules with a regex is banned" here — a regex once ate a
# <link> whose href was a data-URI SVG. Steps below that touch a *shared*
# selector list (not a whole standalone block) are therefore NOT automated —
# they print instructions pointing at tools/dev/cssprune.js / prune-apply.js,
# the project's own sanctioned tool, instead of cutting text themselves.
#
# Run with `bash audit/cleanup.sh` from the repo root. Re-run `git status`
# and `git diff` after each step before committing — this script stages
# nothing and commits nothing on its own.

set -euo pipefail
cd "$(dirname "$0")/.."

confirm() {
  read -r -p "$1 [y/N] " reply
  [[ "$reply" =~ ^[Yy]$ ]]
}

echo "== audit/cleanup.sh — Zero-Touch audit cleanup steps =="
echo "Repo root: $(pwd)"
echo

# ---------------------------------------------------------------------------
# Already resolved at STATE 5 re-verification time — nothing to do, listed
# here only so the record is complete and nobody re-investigates them.
# ---------------------------------------------------------------------------
echo "-- C1 (node_modules committed) -- already resolved, skipping."
echo "   Verified: \`git ls-files node_modules | wc -l\` = 0, .gitignore has node_modules/."
echo "-- C5 (.atlas-*/.mat-*/.dia- dead classes) -- already resolved, skipping."
echo "   Verified: zero matches anywhere in the repo (SUMMARY.md's removal claim holds)."
echo

# ---------------------------------------------------------------------------
# C6 — 11 dead bentofy() calls in tools/partner_template.html targeting
# sections that were "retired outright" per the template's own comment.
# JS statement removal, not CSS-selector surgery — safe to automate with a
# guard: only touches lines that still match the exact dead call signature.
# ---------------------------------------------------------------------------
echo "-- C6: dead bentofy() calls in tools/partner_template.html --"
DEAD_BENTOFY_IDS="p-brief p-material p-shipping p-freight p-war p-tariff p-news p-keynews p-regcal p-report p-season"
FOUND=0
for id in $DEAD_BENTOFY_IDS; do
  if grep -q "bentofy('$id'" tools/partner_template.html 2>/dev/null; then
    FOUND=$((FOUND+1))
  fi
done
echo "   Found $FOUND/11 expected dead bentofy() calls still present."
if [[ "$FOUND" -gt 0 ]]; then
  echo "   These call bentofy() for section ids that verify-desks.js and this audit"
  echo "   confirmed do not exist in the live DOM. bentofy()'s own first line"
  echo "   (var sec=document.getElementById(id);if(!sec)return;) makes each call a"
  echo "   guaranteed no-op — deleting the call lines is behavior-neutral."
  echo "   MANUAL STEP (not automated): open tools/partner_template.html, remove the"
  echo "   bentofy() call lines for: $DEAD_BENTOFY_IDS"
  echo "   Then rebuild (node tools/dev/build.js) and diff partner.html/cost-desk.html"
  echo "   to confirm the rebuild is otherwise unchanged, and re-run verify-desks.js."
fi
echo

# ---------------------------------------------------------------------------
# C7, C9, C10, C11 — dead CSS selector removal. NOT automated: these are
# shared-selector-list or mixed-live/dead-selector cases (C11 explicitly has
# a live selector, .section-intro, sharing a @media block with dead ones).
# Per this project's own rule, cutting CSS by regex/line-range is banned.
# ---------------------------------------------------------------------------
echo "-- C7, C9, C10, C11: dead CSS -- NOT automated, manual + cssprune.js required --"
cat <<'EOF'
   These four findings all involve removing specific *selectors* from rules
   that may also contain live selectors (C11 confirmed this explicitly: a
   dead .map-label/.customer-core/.proof-grid/.proof-card/.handoff-strip
   selector list shares one @media(max-width:760px) block with the live
   .section-intro selector). Per tools/dev/README.md's own stated rule,
   cutting CSS by regex or raw line-range here is banned -- a past incident
   took an unrelated <link> tag down with a regex that matched too much.

   The sanctioned path is tools/dev/cssprune.js (a brace-matching parser)
   driven by tools/dev/prune-apply.js's per-file dead-token lists. To clean
   these up:
     1. Add an entry to prune-apply.js's TARGETS table for each file:
          about.html            -> remove .bd-numbers/.bd-boundary/.bd-side/
                                     .bd-side-birdland/.bd-rule/.bd-firewall (C10)
          tools/team_template.html -> remove the --pos/--neg declarations,
                                     lines 10-11 (C9)
          tools/partner_template.html -> remove .wl/.tm rule selectors (C7),
                                     the .blk-h .tog/.lights override + the
                                     dead bubble-phase click handler (C8)
          tools/news_template.html -> remove the ~24 dead selectors + the
                                     2 unused @keyframes, lines 16-72 (C11) --
                                     KEEP .section-intro, it's live
     2. Run: node -e "require('./tools/dev/prune-apply.js')" (check
        tools/dev/README.md's exact invocation -- prune-apply.js "aborts if
        brace balance changes", so a failed run is safe, not silently wrong)
     3. Rebuild every affected page and diff against main before committing.
   C10's dead block also carries one incidental token-drift fix (a hardcoded
   #ece7dc that snap-color.js flagged as within Δ14 of --paper-2) -- gone
   automatically once the block is removed, no separate step needed.
EOF
echo

# ---------------------------------------------------------------------------
# C4/D43 — I-7 token-shadowing removal (partner_template.html, team_template.html,
# site-shell.css). This is a full standalone rule/declaration-block removal,
# not a selector-list edit, so it's lower-risk than C7/C9-C11 above -- but it's
# still a live-site CSS behavior change with a real (if minor) visual effect
# on 5 pages, so it stays manual/reviewed rather than blindly automated.
# ---------------------------------------------------------------------------
echo "-- C4/D43: I-7 token-shadowing removal -- manual, review the visual diff --"
cat <<'EOF'
   Recommended (not automated): remove the shadow blocks entirely and let
   these files fall through to tokens.css's canonical --up/--down/--flat/--line,
   which executive.html and my-market.html already render correctly:
     - tools/partner_template.html: the body.theme-light block redefining
       --down/--up/--flat/--line (affects partner.html + cost-desk.html)
     - tools/team_template.html:10-11: the --pos/--neg block (dead anyway,
       see C9 above -- removing it for C9 also resolves this)
     - site-shell.css:5's --line redefinition (affects guide.html + the
       3 redirect stubs that load it)
   After removing, rebuild all affected pages and visually check the header
   hairline color on each -- expect it to become consistent with
   executive.html/my-market.html's current (correct) rendering.
EOF
echo

# ---------------------------------------------------------------------------
# C2 — stale branch origin/codex/pr-validation. Branch deletion is
# irreversible and out of scope for a file-cleanup script; flagged for a
# human to action directly via git/GitHub, not via this script.
# ---------------------------------------------------------------------------
echo "-- C2: origin/codex/pr-validation branch -- NOT in this script, human action only --"
echo "   This branch is ~365 files / ~69k lines behind current main's content --"
echo "   confirmed abandoned, not in-progress work (DECISIONS.md D2)."
echo "   If you want it gone: git push origin --delete codex/pr-validation"
echo "   (run this yourself when ready -- deleting a branch is irreversible and"
echo "   this script will not do it for you)."
echo

# ---------------------------------------------------------------------------
# C3 — birdland-intro.html orphan deletion already exists on the unpushed
# i18n/my-market-composed-sentences branch. Not this script's job to
# duplicate; resolved by pushing/merging that branch instead.
# ---------------------------------------------------------------------------
echo "-- C3: birdland-intro.html deletion -- already exists on another branch, skipping --"
echo "   Fix lives on i18n/my-market-composed-sentences (unpushed, see the audit's"
echo "   top-of-report risk reminder). Push/merge that branch rather than re-doing"
echo "   the deletion here -- doing both would just create a merge conflict."
echo

echo "== Done. Review 'git status'/'git diff' for anything you applied manually above. =="
