(function(){
'use strict';
var root=document.querySelector('[data-guided-tools]');if(!root)return;
var site=window.BL_SITE,id='en';try{id=localStorage.getItem('bl_lang')||id;}catch(e){}
var language=site.languages.find(l=>l.id===id)||site.languages[0];function t(k){return language.text[k]||site.languages[0].text[k]||k;}
function el(id){return document.getElementById(id);}function money(n){return 'US$'+n.toLocaleString(language.tag,{minimumFractionDigits:2,maximumFractionDigits:2});}
var snapshots={};
// Preserve inputs, but require review before applying them to a different selection.
var focus=window.BL_FOCUS,pendingReview=false;
function contextKey(state){return[state.category||'',state.market||'',state.product||''].join('|');}
var lastContext=contextKey(focus.get()),confirmedContext=lastContext;
function hasCostInputs(){return Array.from(el('bt-cost-form').querySelectorAll('input[type="number"]')).some(input=>input.value!=='');}
var review=document.createElement('div');review.id='bt-context-review';review.className='bt-context-review';review.hidden=true;review.setAttribute('role','status');
var reviewTitle=document.createElement('strong'),reviewBody=document.createElement('p'),reviewActions=document.createElement('div');
reviewTitle.textContent=t('fxContextTitle');reviewBody.textContent=t('fxContextBody');
function reviewButton(id,key,action){var button=document.createElement('button');button.type='button';button.id=id;button.textContent=t(key);button.addEventListener('click',action);reviewActions.append(button);}
reviewButton('bt-review-inputs','fxContextEdit',()=>{el('bt-estimate-inputs').open=true;el('bt-fob').focus();el('bt-cost-form').scrollIntoView({block:'start',behavior:'auto'});});
reviewButton('bt-confirm-context','fxContextConfirm',()=>{confirmedContext=contextKey(focus.get());pendingReview=false;cost();mobileResult();});
review.append(reviewTitle,reviewBody,reviewActions);el('bt-estimate-inputs').before(review);
function clearCopiedCost(){el('bt-copy-status').textContent='';el('bt-copy-fallback').hidden=true;el('bt-copy-fallback').value='';}
function changedContext(state){var next=contextKey(state);if(next===lastContext)return;lastContext=next;if(!hasCostInputs())confirmedContext=next;pendingReview=hasCostInputs()&&next!==confirmedContext;clearCopiedCost();cost();mobileResult();}
focus.on(changedContext);
function mobileResult(){var panel=root.querySelector('[data-tool-panel]:not([hidden])'),kind=panel?.id==='landed-cost'?'cost':panel?.id==='reorder-planning'?'stock':null,bar=el('bt-mobile-result');bar.hidden=!kind||!snapshots[kind];el('bt-mobile-value').textContent=kind==='cost'?el('bt-unit').textContent:kind==='stock'?el('bt-order-date').textContent:'';}
el('bt-view-result').addEventListener('click',()=>{var result=root.querySelector('[data-tool-panel]:not([hidden]) .bt-result');if(result){result.setAttribute('tabindex','-1');result.focus({preventScroll:true});result.scrollIntoView({block:'center',behavior:'smooth'});}});
el('bt-lead-details').addEventListener('toggle',()=>{el('bt-total-lead').disabled=el('bt-lead-details').open;stock();mobileResult();});
function values(form){return Object.fromEntries(new FormData(form).entries());}
function validity(form){var invalid=false;form.querySelectorAll('input[type="number"]').forEach(input=>{var bad=input.value!==''&&!input.validity.valid;input.setAttribute('aria-invalid',String(bad));invalid=invalid||bad;});return invalid;}
function cost(){if(!hasCostInputs()){pendingReview=false;confirmedContext=contextKey(focus.get());}review.hidden=!pendingReview;var v=values(el('bt-cost-form')),r=pendingReview?null:window.BL_BUYER_MODELS.cost(v),invalid=validity(el('bt-cost-form'));snapshots.cost=null;['bt-unit','bt-cash','bt-tax-amount','bt-price'].forEach(id=>el(id).textContent='—');el('bt-cost-empty').textContent=t(pendingReview?'fxContextEmpty':invalid?'btCheckInputs':'biPlanNote');el('bt-cost-result').hidden=!r;el('bt-cost-empty').hidden=!!r;el('bt-cost-copy').disabled=!r;el('bt-cost-result').closest('aside').hidden=!r&&!invalid&&!pendingReview;el('bt-cost-form').closest('.bt-workspace').classList.toggle('bt-no-result',!r&&!invalid&&!pendingReview);var assumption=el('bt-cost-form').querySelector('.br-assumption');if(!assumption){assumption=document.createElement('p');assumption.className='br-assumption';el('bt-cost-form').append(assumption);}assumption.textContent=t('brTaxUnknown');if(!r)return;
 el('bt-unit').textContent=money(r.unit);el('bt-cash').textContent=money(r.total);el('bt-tax-amount').textContent=money(r.taxAmount);el('bt-price').textContent=r.price===null?'—':money(r.price);el('bt-cost-assumptions').textContent=t('btAssumptions')+': '+t('btDuty')+' '+(v.duty||0)+'%; '+t('btTax')+' '+(v.tax||0)+'%; '+t('btBasis')+' '+v.basis.toUpperCase()+'.';
 snapshots.cost=['Birdland · Buyer cost scenario (USD)',`FOB ${v.fob} | Qty ${v.quantity} | Freight ${v.freight} | Insurance ${v.insurance||0} | Fees ${v.fees||0}`,`Duty ${v.duty||0}% (${v.basis.toUpperCase()}) | Import tax ${v.tax||0}% (CIF + duty)`,`Landed cost/unit before import tax: ${money(r.unit)}`,`Total cash requirement: ${money(r.total)} | Import tax: ${money(r.taxAmount)}`,r.price===null?'':`Selling price before sales tax at ${v.margin}% gross margin: ${money(r.price)} (import tax ${v.includeTax==='on'?'included':'excluded'} in cost)`,t('brTaxUnknown')+' User assumptions only; not a Birdland quotation. Rates and customs valuation must be confirmed with your broker.'].filter(Boolean).join('\n');
}
function stock(){var v=values(el('bt-stock-form'));v.mode=el('bt-lead-details').open?'split':'total';v.now=new Date().toISOString();var r=window.BL_BUYER_MODELS.stock(v),invalid=validity(el('bt-stock-form'));snapshots.stock=null;el('bt-stock-empty').textContent=t(invalid?'btCheckInputs':'btStockEmpty');el('bt-stock-result').hidden=!r;el('bt-stock-empty').hidden=!!r;el('bt-stock-copy').disabled=!r;if(!r)return;
 el('bt-order-date').textContent=r.now?t('btOrderNow'):r.date;el('bt-cover').textContent=r.cover.toFixed(1);el('bt-pipeline').textContent=r.pipeline.toFixed(1);el('bt-threshold').textContent=r.threshold.toLocaleString(language.tag);
 snapshots.stock=['Birdland · Buyer reorder scenario',`Stock ${v.stock} | Weekly sales ${v.weekly} | Total lead including buffer ${r.pipeline} weeks` ,`Reorder by: ${r.now?'Order now':r.date} | Cover ${r.cover.toFixed(1)} weeks | Reorder threshold ${r.threshold} units`,'User assumptions only; not a promised production or delivery date. Assumes steady weekly demand; excludes orders already on the way.'].join('\n');
}
['cost','stock'].forEach(kind=>{var form=el('bt-'+kind+'-form'),calculate=kind==='cost'?cost:stock;form.addEventListener('submit',e=>e.preventDefault());function update(){calculate();mobileResult();}form.addEventListener('input',update);form.addEventListener('change',update);form.addEventListener('reset',()=>{if(kind==='cost'){pendingReview=false;confirmedContext=contextKey(focus.get());}setTimeout(update,0);clearCopiedCost();});calculate();el('bt-'+kind+'-copy').addEventListener('click',async()=>{var text=snapshots[kind];if(!text)return;try{await navigator.clipboard.writeText(text);el('bt-copy-status').textContent=t('btCopied');}catch(e){var fallback=el('bt-copy-fallback');fallback.hidden=false;fallback.value=text;fallback.focus();fallback.select();el('bt-copy-status').textContent=t('btCopyFallback');}});});
var aliases={'cost-sensitivity':'cost-trends','p-landed2':'landed-cost','p-margin':'landed-cost','p-reorder':'reorder-planning','p-sail':'reorder-planning','p-cduty':'landed-cost','p-mkt':'cost-trends'};
function show(){var hash=location.hash.slice(1),id=aliases[hash]||hash;if(!['landed-cost','reorder-planning','cost-trends'].includes(id))id='landed-cost';root.querySelectorAll('[data-tool-panel]').forEach(panel=>panel.hidden=panel.id!==id);root.querySelectorAll('[data-tool-link]').forEach(a=>{if(a.hash==='#'+id)a.setAttribute('aria-current','true');else a.removeAttribute('aria-current');});if(hash==='cost-sensitivity')el('cost-sensitivity').open=true;mobileResult();}
root.querySelectorAll('[data-tool-link]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();if(location.hash!==a.hash)history.pushState(null,'',a.hash);show();el(a.hash.slice(1)).querySelector('h2').focus({preventScroll:true});el(a.hash.slice(1)).scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}));
root.querySelectorAll('[data-quote-mode]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();el('bt-estimate-inputs').open=true;el('bt-fob').focus();el('bt-estimate-inputs').scrollIntoView({block:'start'});}));
window.addEventListener('bl:clear-preferences',()=>{el('bt-cost-form').reset();el('bt-stock-form').reset();clearCopiedCost();});window.addEventListener('hashchange',show);window.addEventListener('popstate',show);show();
})();
