/* One enquiry format. Explicit tab-scoped handoff only; no contact or cost ingestion. */
(function(){
'use strict';
const KEY='bl_enquiry_handoff',TTL=30*60*1000,adapters=new Map();let draft={version:1,items:[],note:''},dialog,view,opener;
const script=document.querySelector('script[src*="buyer-brief.js"]'),base=new URL('.',script.src),file=location.pathname.split('/').pop(),isContact=file==='contact.html';
function language(){let id=document.documentElement.lang;try{id=localStorage.getItem('bl_lang')||id;}catch(e){}return window.BL_SITE.languages.find(l=>l.id===id||l.tag===id)||window.BL_SITE.languages[0];}
function t(k){return language().text[k]||window.BL_SITE.languages[0].text[k]||k;}
const text=v=>typeof v==='string'?v.slice(0,4000):'';
function cleanReference(value){const keys=['family','model','part','material','process'];if(!value||!keys.every(k=>Number.isInteger(value[k])&&value[k]>=0&&value[k]<=1000))return null;return Object.fromEntries(keys.map(k=>[k,value[k]]));}
function clean(value){if(!value||value.version!==1||!Array.isArray(value.items))return {version:1,items:[],note:''};return {version:1,note:text(value.note),items:value.items.slice(0,100).filter(i=>i&&typeof i.id==='string'&&typeof i.source==='string').map(i=>({id:text(i.id),source:text(i.source),title:text(i.title),selected:(Array.isArray(i.selected)?i.selected:[]).filter(x=>typeof x==='string').slice(0,60).map(text),unknown:(Array.isArray(i.unknown)?i.unknown:[]).filter(x=>typeof x==='string').slice(0,60).map(text),inputs:{quantity:Number.isInteger(Number(i.inputs?.quantity))&&Number(i.inputs?.quantity)>0?Number(i.inputs.quantity):'',date:/^\d{4}-\d{2}$/.test(i.inputs?.date||'')?i.inputs.date:'',notes:text(i.inputs?.notes),studio:i.source==='Product Studio'?{mode:i.inputs?.studio?.mode==='model'?'model':'idea',model:text(i.inputs?.studio?.model),category:text(i.inputs?.studio?.category),use:text(i.inputs?.studio?.use),priorities:Array.isArray(i.inputs?.studio?.priorities)?i.inputs.studio.priorities.filter(x=>typeof x==='string').slice(0,2):[],material:text(i.inputs?.studio?.material),process:text(i.inputs?.studio?.process),part:text(i.inputs?.studio?.part),referenceRoute:cleanReference(i.inputs?.studio?.referenceRoute),recommend:i.inputs?.studio?.recommend!==false}:null},examples:(Array.isArray(i.examples)?i.examples:[]).filter(x=>typeof x==='string').slice(0,60).map(text)}))};}
function recall(){try{const v=JSON.parse(sessionStorage.getItem(KEY)||'null');if(v&&v.expires>Date.now()){draft=clean(v.draft);return true;}sessionStorage.removeItem(KEY);}catch(e){try{sessionStorage.removeItem(KEY);}catch(ignore){}}return false;}
recall();
function format(value=draft){const d=clean(value);let out=['BIRDLAND — '+t('brTitle'),''];for(const i of d.items){out.push(i.title+' ['+i.source+']');for(const [k,a] of [['brSelected',i.selected],['brUnknown',i.unknown],['brExample',i.examples]])if(a.length)out.push(t(k)+':',...a.map(s=>'  • '+s));out.push('');}if(d.note.trim())out.push(t('brNote')+':',d.note.trim(),'');out.push(t('brDraft'));return out.join('\n');}
function persist(){try{sessionStorage.setItem(KEY,JSON.stringify({expires:Date.now()+TTL,draft:clean(draft)}));return true;}catch(e){return false;}}
function node(tag,cls,value){const e=document.createElement(tag);if(cls)e.className=cls;if(value)e.textContent=value;return e;}
function button(key,action,cls){const b=node('button',cls,t(key));b.type='button';b.dataset.brLabel=key;b.addEventListener('click',action);return b;}
function download(){const a=node('a');a.href=URL.createObjectURL(new Blob([format()],{type:'text/plain;charset=utf-8'}));a.download='birdland-enquiry.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function status(value){if(view)view.querySelector('[role="status"]').textContent=value;document.querySelectorAll('.br-clear-status').forEach(e=>e.textContent=value);}
function refresh(){if(!view)return;const list=view.querySelector('.br-items');list.replaceChildren();for(const i of draft.items){const row=node('article','br-item'),head=node('div','br-item-head'),h=node('h3','',i.title);head.append(h);const remove=button('catRemove',()=>{draft.items=draft.items.filter(x=>!(x.id===i.id&&x.source===i.source));adapters.get(i.source)?.remove?.(i.id);if(isContact)persist();refresh();const remaining=view.querySelectorAll('.br-item-head button');(remaining[0]||view.querySelector('.br-note')).focus({preventScroll:true});status(t('brRemoved'));});remove.setAttribute('aria-label',t('catRemove')+' '+i.title);head.append(remove);const routes={Products:'products.html',Configurator:'configurator.html?product='+encodeURIComponent(i.id),'Product Studio':'partner.html#studio-needs'};if(routes[i.source]){const link=node('a','br-edit',t('brEdit'));const l=language(),name=routes[i.source];link.href=new URL((name.startsWith('configurator.html')&&l.id!=='en'?l.id+'/':'')+name,base).href;link.addEventListener('click',persist);head.append(link);}row.append(head,node('small','br-source',i.source));for(const [k,values]of [['brSelected',i.selected],['brUnknown',i.unknown],['brExample',i.examples]])if(values.length){row.append(node('h4','',t(k)));const ul=node('ul');values.forEach(v=>ul.append(node('li','',v)));row.append(ul);}list.append(row);}view.querySelector('.br-empty').hidden=!!draft.items.length;view.querySelector('.br-preview').value=format();const note=view.querySelector('.br-note');if(document.activeElement!==note)note.value=draft.note;view.querySelectorAll('[data-br-label]').forEach(e=>e.textContent=t(e.dataset.brLabel));}
async function copy(){try{await navigator.clipboard.writeText(format());status(t('brCopied'));}catch(e){const p=view.querySelector('.br-preview');p.closest('details').open=true;p.focus();p.select();status(t('brFallback'));}}
function contactURL(){const l=language();return new URL((l.id==='en'?'':l.id+'/')+'contact.html#enquiry',base).href;}
function makeView(){const e=node('section','br-workspace');e.setAttribute('translate','no');e.append(node('h2','',t('brTitle')),node('p','br-empty',t(isContact&&location.hash==='#enquiry'?'brExpired':'brEmpty')),node('div','br-items'));const label=node('label','br-note-label',t('brNote')),note=node('textarea','br-note');note.maxLength=2000;note.rows=3;label.append(note);note.addEventListener('input',()=>{draft.note=note.value;e.querySelector('.br-preview').value=format();});e.append(label);const preview=node('textarea','br-preview');preview.readOnly=true;preview.rows=7;preview.setAttribute('aria-label',t('brReview'));const details=node('details','br-text-preview');details.append(node('summary','',t('brReview')),preview);e.append(details);const act=node('div','br-actions');act.append(button('brCopy',copy),button('brDownload',download),button('brClear',()=>{adapters.forEach(a=>a.clear?.());draft={version:1,items:[],note:''};try{sessionStorage.removeItem(KEY);}catch(e){}refresh();}));if(!isContact)act.append(button('brContact',()=>{if(persist())location.assign(contactURL());else{status(t('brFallback'));preview.closest('details').open=true;preview.focus();preview.select();}} ,'br-primary'));e.insertBefore(act,e.querySelector('.br-items'));e.append(node('p','br-small',t('brPrivate')),node('p','br-small',t('brDraft')));const s=node('p','br-status');s.setAttribute('role','status');e.append(s);return e;}
function open(source){const a=adapters.get(source);if(a){const snap=clean({version:1,items:a.snapshot(),note:''});draft.items=draft.items.filter(i=>i.source!==source).concat(snap.items);}opener=document.activeElement;if(!dialog){dialog=node('dialog','br-dialog');dialog.setAttribute('aria-label',t('brReview'));dialog.append(button('brClose',()=>dialog.close(),'br-close'));view=makeView();dialog.append(view);document.body.append(dialog);dialog.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const controls=[...dialog.querySelectorAll('button,a[href],input,textarea,select,summary')].filter(n=>!n.disabled&&n.getClientRects().length&&(!n.closest('details:not([open])')||(n.tagName==='SUMMARY'&&n.parentElement===n.closest('details:not([open])'))));const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});dialog.addEventListener('close',()=>{const target=opener?.isConnected?opener:document.querySelector('.sn-brief .br-entry,#mailBtn,#cat-enq .br-entry');target?.focus?.({preventScroll:true});});}refresh();if(!dialog.open)dialog.showModal();}
function register(source,adapter){adapters.set(source,adapter);}
function clearDevice(){const localKeys=['bl-cat','bl_cfg_sheet','bl_buyer_focus','bl_buyer_seen','bl_ctx','bl_mr_region','bl_mr_line','bd_p_room','bd_p_region','bd_bc_co','bl_lang','bl_intro_seen','bl_fol_cut','bl_mm_compare','bl_market_choice'];try{localKeys.forEach(k=>localStorage.removeItem(k));[KEY,'bl_cfg_tab','bl_enquiry_cart_2'].forEach(k=>sessionStorage.removeItem(k));}catch(e){}draft={version:1,items:[],note:''};adapters.forEach(a=>a.clear?.());window.BL_FOCUS?.clear();try{localKeys.forEach(k=>localStorage.removeItem(k));}catch(e){}refresh();window.dispatchEvent(new Event('bl:clear-preferences'));status(t('brCleared'));}
function init(){document.body.classList.add('bl-experience');let backdropDown=null;document.addEventListener('pointerdown',e=>{backdropDown=null;if(e.target instanceof HTMLDialogElement){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)backdropDown=e.target;}});document.addEventListener('click',e=>{document.querySelectorAll('.bj-language[open]').forEach(menu=>{if(!menu.contains(e.target))menu.open=false;});const d=e.target;if(d instanceof HTMLDialogElement&&d.open&&d===backdropDown){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.bj-language[open]').forEach(menu=>{menu.open=false;menu.querySelector('summary')?.focus({preventScroll:true});});});const about=file==='about.html';if(about){const copy=document.querySelector('.ledger-copy,.about-hero');if(copy){const focus=node('p','br-capability',t('catMetalIntro')+' '+t('catSupport'));copy.append(focus);}}if(isContact){view=makeView();view.id='enquiry';const route=document.querySelector('.mail-route');route.append(view);refresh();const openMail=document.getElementById('mr-open');view.querySelector('.br-actions').prepend(openMail);openMail.classList.add('br-primary');openMail.textContent=t('brOpen');const caption=document.querySelector('.ledger-caption');if(caption)caption.prepend(node('small','br-source',t('brComposite')+' · '));openMail.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();const M=window.blMail;if(!M)return;if(!draft.items.length&&!draft.note.trim()){status(t('brEmpty'));view.querySelector('.br-note').focus();return;}const body=format(),long=encodeURIComponent(body).length>6000;try{M.open(document.getElementById('mr-region').value,document.getElementById('mr-line').value,'Birdland OEM enquiry',long?t('brLong'):body,'brief');}catch(err){}status((long?t('brLong')+' ':'')+t('brAttempt'));},true);if(location.hash==='#enquiry')view.scrollIntoView({block:'start'});}
const footer=document.querySelector('body>footer,.bl-footer');const settings=node('details','br-settings');settings.setAttribute('translate','no');const sum=node('summary','',t('brDevice')),clearStatus=node('p','br-clear-status');clearStatus.setAttribute('role','status');settings.append(sum,button('brDevice',clearDevice),clearStatus);(footer||document.body).append(settings);document.addEventListener('click',e=>{if(isContact&&e.target.closest('.bj-language a'))persist();});}
window.BL_BRIEF={replaceSource(source,items){draft.items=draft.items.filter(i=>i.source!==source).concat(clean({version:1,items,note:''}).items);},register,open,format,clearDevice,t,items(source){return clean(draft).items.filter(i=>i.source===source);}};
document.addEventListener('DOMContentLoaded',init,{once:true});window.addEventListener('bl:lang',refresh);
})();
