/* Official catalogue references. Static data; only public selections persist. */
(function () {
'use strict';
var C=window.BL_CATALOG,root=document.getElementById('bl-cat');
if(!C||!root||(window.BL_DESK&&window.BL_DESK!=='buyer'))return;
var byId={},categories=C.categories||[],quantities={},notes='',sizeChoice={},visible=12;
C.products.concat(C.legacy||[]).forEach(function(p){byId[p.id]=p;});
var el={};['rail','q','origin','count','list','detail','enq','enq-list','enq-hint','enq-copy','enq-clear','enq-open','enq-count','notes'].forEach(function(k){el[k]=document.getElementById('cat-'+k);});
function t(key){var lang='en';try{lang=localStorage.getItem('bl_lang')||'en';}catch(e){}var editions=window.BL_SITE.languages;var edition=editions.find(function(l){return l.id===lang;})||editions[0];return edition.text[key]||editions[0].text[key]||key;}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function origin(p){return t(p.origin==='TW'?'catTaiwan':'catChina');}
function parts(key){var split=key.split('::');return {p:byId[split[0]],size:split[1]||''};}
function validKey(key){if(typeof key!=='string')return false;var item=parts(key);return !!item.p&&(!item.size||(item.p.sizes||[]).indexOf(item.size)>=0);}
var st={axis:'',q:'',origin:'',pick:'',enq:[]};
try{var old=JSON.parse(localStorage.getItem('bl-cat')||'{}');['axis','origin','pick'].forEach(function(k){if(typeof old[k]==='string')st[k]=old[k];});st.enq=Array.isArray(old.enq)?Array.from(new Set(old.enq.filter(validKey))):[];}catch(e){}
if(!categories.some(function(c){return c.id===st.axis;}))st.axis='';
if(!['','TW','CN'].includes(st.origin))st.origin='';
if(!byId[st.pick])st.pick='';
var skuQuery=new URLSearchParams(location.search).get('sku');
if(skuQuery){st.q=skuQuery;st.axis='';st.origin='';var match=C.products.find(function(p){return p.sku.toLowerCase().replace(/[^a-z0-9]/g,'')===skuQuery.toLowerCase().replace(/[^a-z0-9]/g,'');});st.pick=match?match.id:'';}
function save(){if(window.BL_FOCUS){var selected=byId[st.pick];if(st.axis&&(!selected||selected.axis!==st.axis))window.BL_FOCUS.set({category:st.axis,product:''});else if(selected&&!selected.legacy)window.BL_FOCUS.set({category:selected.axis,product:selected.id});else if(st.axis)window.BL_FOCUS.set({category:st.axis,product:''});}try{localStorage.setItem('bl-cat',JSON.stringify({...st,q:''}));}catch(e){}}
function matches(p){var q=st.q.trim().toLowerCase();if(!q)return true;var normalized=q.replace(/[^a-z0-9]/g,'');if(normalized&&p.sku.toLowerCase().replace(/[^a-z0-9]/g,'').includes(normalized))return true;var hay=[p.sku,p.name,t(categories.find(function(c){return c.id===p.axis;}).label),origin(p)].concat(Object.values(p.specs)).join(' ').toLowerCase();return q.split(/\s+/).every(function(w){return hay.includes(w);});}
function pool(){return C.products.filter(function(p){return (!st.origin||p.origin===st.origin)&&matches(p);});}
function renderRail(){var products=pool(),rows=[{id:'',label:'catAll'}].concat(categories);el.rail.innerHTML=rows.map(function(c){var n=products.filter(function(p){return !c.id||p.axis===c.id;}).length;return '<button type="button" data-axis="'+esc(c.id)+'" aria-current="'+(st.axis===c.id)+'">'+esc(t(c.label))+'<em>'+n+'</em></button>';}).join('');}
function renderList(){var rows=pool().filter(function(p){return !st.axis||p.axis===st.axis;});el.count.textContent=rows.length+' '+t('catModels');var more=document.getElementById('cat-more');more.hidden=rows.length<=visible;more.textContent=t('catMore')+' ('+Math.max(0,rows.length-visible)+')';el.list.innerHTML=rows.length?rows.slice(0,visible).map(function(p,i){var multi=p.sizes.length>1,on=st.enq.some(function(k){return parts(k).p.id===p.id;});return '<li class="cat-row" tabindex="0" data-id="'+esc(p.id)+'" data-selected="'+(st.pick===p.id)+'"><img src="'+esc(p.img)+'" alt="'+esc(p.sku+' '+p.name)+'" loading="'+(i<6?'eager':'lazy')+'" width="240" height="180"><div><div class="cat-sku">'+esc(p.sku)+'</div><div class="cat-nm">'+esc(p.name)+'</div><div class="cat-why">'+esc(p.specs.length)+'</div><div class="cat-meta"><span class="cat-badge">'+esc(origin(p))+'</span></div></div><button type="button" class="cat-add" data-add="'+esc(p.id)+'" aria-pressed="'+on+'">'+esc(t(multi?'catChooseSize':on?'catOnList':'catAdd'))+'</button></li>';}).join(''):'<li class="cat-empty">'+esc(t('catEmpty'))+'</li>';}
function renderDetail(){var p=byId[st.pick];if(!p){el.detail.innerHTML='<h3>'+esc(t('catPick'))+'</h3><p class="cat-hint">'+esc(t('catPickHint'))+'</p>';return;}
var source=C.sources.find(function(s){return s.id===p.source;});
var h=(p.img?'<img class="cat-detail-photo" src="'+esc(p.img)+'" alt="'+esc(p.sku+' '+p.name)+'">':'')+'<p class="cat-sku">'+esc(p.sku||t('catLegacy'))+'</p><h3>'+esc(p.name)+'</h3><p class="cat-hint">'+esc(origin(p))+'</p><dl>';
Object.keys(p.specs||{}).forEach(function(k){h+='<dt>'+esc(t({length:'catLength',material:'catMaterial',handle:'catHandle'}[k]||k))+'</dt><dd>'+esc(p.specs[k])+'</dd>';});h+='</dl>';var missing=['material','handle'].filter(function(k){return !p.specs[k];});if(missing.length)h+='<p class="br-unknown">'+esc(t('brUnknown')+': '+missing.map(k=>t(k==='material'?'catMaterial':'catHandle')).join(', '))+'</p>';
if(p.sizes&&p.sizes.length>1)h+='<label class="cat-size-label">'+esc(t('catChooseSize'))+'<select id="cat-size"><option value="">'+esc(t('catChooseSize'))+'</option>'+p.sizes.map(function(size){return '<option value="'+esc(size)+'"'+(sizeChoice[p.id]===size?' selected':'')+'>'+esc(size)+'</option>';}).join('')+'</select></label>';
if(p.legacy)h+='<p class="cat-hint">'+esc(t('catLegacyHint'))+'</p>';
else h+='<button type="button" class="cat-alt" data-add="'+esc(p.id)+'"'+(p.sizes.length>1&&!sizeChoice[p.id]?' disabled':'')+'>'+esc(t('catAdd'))+'</button><p class="cat-source">'+esc((source?source.title:'')+' · PDF '+t('catPage')+' '+p.page)+'</p>';
if(!p.legacy)h+='<p><a class="br-edit" href="partner.html?sku='+encodeURIComponent(p.sku)+'#studio-needs">'+esc(t('custom'))+' →</a></p>';el.detail.innerHTML=h;}
function renderEnq(){el['enq-list'].innerHTML=st.enq.map(function(key){var item=parts(key),p=item.p;return '<li><div><strong>'+esc(p.sku||t('catLegacy'))+'</strong><br>'+esc(p.name)+'<br><span class="cat-hint">'+esc((item.size||p.specs.length||'')+' · '+origin(p))+'</span><label class="cat-qty-label">'+esc(t('catQty'))+'<input type="number" min="1" max="10000000" step="1" inputmode="numeric" data-qty="'+esc(key)+'" value="'+esc(quantities[key]||'')+'" placeholder="—"></label></div><button type="button" data-drop="'+esc(key)+'" aria-label="'+esc(t('catRemove')+' '+(p.sku||p.name))+'">×</button></li>';}).join('');el['enq-hint'].hidden=!!st.enq.length;el['enq-copy'].disabled=el['enq-clear'].disabled=!st.enq.length;el['enq-copy'].textContent=t('catCopy');el['enq-clear'].textContent=t('catClear');el['enq-count'].textContent=String(st.enq.length);}
function renderAll(){renderRail();renderList();renderDetail();renderEnq();}
// Selection changes do not replace the browsing DOM: preserve focus, images
// and reading position while updating only the affected visual state.
function syncSelection(){el.list.querySelectorAll('.cat-row').forEach(function(row){row.dataset.selected=String(row.dataset.id===st.pick);var button=row.querySelector('[data-add]'),p=byId[row.dataset.id],on=st.enq.some(function(key){return parts(key).p.id===p.id;});button.setAttribute('aria-pressed',String(on));button.textContent=t(p.sizes.length>1?'catChooseSize':on?'catOnList':'catAdd');});var button=el.detail.querySelector('[data-add]'),p=byId[st.pick];if(button&&p){var key=p.id+(p.sizes.length>1?'::'+sizeChoice[p.id]:'');button.disabled=p.sizes.length>1&&!sizeChoice[p.id];button.textContent=t(st.enq.includes(key)?'catOnList':'catAdd');}}
function snapshot(){return st.enq.map(function(key){var item=parts(key),p=item.p;return {id:key,source:'Products',title:p.sku+' · '+p.name,selected:[origin(p),item.size||p.specs.length||''].filter(Boolean).concat(notes.trim()?[t('catNotes')+': '+notes.trim()]:[]).concat(quantities[key]?[t('catQty')+': '+quantities[key]]:[]),unknown:[!quantities[key]?t('catQty'):'',!p.specs.material?t('catMaterial'):'',!p.specs.handle?t('catHandle'):''].filter(Boolean),inputs:{quantity:quantities[key]||'',notes},examples:[t('catSourceNote')]};});}
if(window.BL_BRIEF){for(const item of window.BL_BRIEF.items('Products'))if(st.enq.includes(item.id)){quantities[item.id]=item.inputs.quantity||'';notes=item.inputs.notes||notes;}el.notes.value=notes;window.BL_BRIEF.register('Products',{snapshot,remove:function(key){st.enq=st.enq.filter(k=>k!==key);delete quantities[key];save();renderAll();},clear:function(){clearTimeout(timer);st.enq=[];st.q='';st.axis='';st.origin='';st.pick='';quantities={};notes='';el.notes.value='';el.q.value='';el.origin.value='';renderAll();}});var review=document.createElement('button');review.type='button';review.className='br-entry';review.textContent=t('brReview');review.addEventListener('click',()=>window.BL_BRIEF.open('Products'));el.enq.querySelector('.cat-enq-act').appendChild(review);}
function enquiryText(){if(window.BL_BRIEF)return window.BL_BRIEF.format({version:1,items:snapshot(),note:''});var lines=['BIRDLAND — PRODUCT ENQUIRY','','SKU | PRODUCT | ORIGIN | QTY | SIZE'];st.enq.forEach(function(key){var item=parts(key),p=item.p;lines.push((p.sku||'CAPABILITY REFERENCE: '+p.id)+' | '+p.name+' | '+(p.origin==='TW'?'Taiwan':'China')+' | '+(quantities[key]||'To confirm')+' | '+(item.size||p.specs.length||'To confirm'));});if(notes.trim())lines.push('','Requirements: '+notes.trim());lines.push('','Please confirm the available specification and suitability for our project.');return lines.join('\n');}
function copy(){var value=enquiryText();function done(){el['enq-copy'].textContent=t('catCopied');setTimeout(function(){el['enq-copy'].textContent=t('catCopy');},1600);}function fallback(){var field=document.createElement('textarea');field.value=value;field.className='cat-copy-fallback';el.enq.appendChild(field);field.select();if(document.execCommand('copy')){field.remove();done();}else{field.focus();field.setAttribute('aria-label',t('catCopy'));}}if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(value).then(done,fallback);else fallback();}
var productDialog,enquiryDialog,productParent=el.detail.parentNode,enquiryParent=el.enq.parentNode;
function dialog(kind){var isProduct=kind==='product',existing=isProduct?productDialog:enquiryDialog;if(existing)return existing;var node=document.createElement('dialog');node.className=isProduct?'cat-product-dialog':'cat-enquiry-dialog';node.setAttribute('aria-label',t(isProduct?'catSpecifications':'catEnquiry'));var back=document.createElement('button');back.type='button';back.className='cat-dialog-back';back.textContent=t('backProducts');back.addEventListener('click',function(){node.close();});node.appendChild(back);node.addEventListener('close',function(){var active=document.activeElement,restoreFocus=!active||active===document.body||node.contains(active);if(isProduct){productParent.insertBefore(el.detail,productParent.firstChild);var row=el.list.querySelector('[data-selected="true"]');if(row&&restoreFocus)row.focus({preventScroll:true});}else{enquiryParent.appendChild(el.enq);if(restoreFocus)el['enq-open'].focus({preventScroll:true});}});root.appendChild(node);if(isProduct)productDialog=node;else enquiryDialog=node;return node;}
function openProduct(id){st.pick=id;save();syncSelection();renderDetail();syncSelection();var d=dialog('product');d.appendChild(el.detail);d.scrollTop=0;if(!d.open)d.showModal();}
function add(id){var p=byId[id];if(!p||p.legacy)return;if(p.sizes.length>1&&!sizeChoice[id]){openProduct(id);var select=document.getElementById('cat-size');if(select)select.focus({preventScroll:true});return;}var key=id+(p.sizes.length>1?'::'+sizeChoice[id]:'');if(!st.enq.includes(key))st.enq.push(key);save();syncSelection();renderEnq();}
el.rail.addEventListener('click',function(e){var b=e.target.closest('[data-axis]');if(b){st.axis=b.dataset.axis;visible=12;save();renderRail();renderList();var target=Array.from(el.rail.querySelectorAll('[data-axis]')).find(function(n){return n.dataset.axis===st.axis;});if(target)target.focus({preventScroll:true});}});
var timer;el.q.value=st.q;el.q.placeholder=t('catSearch');el.q.setAttribute('aria-label',t('catSearch'));el.q.addEventListener('input',function(){clearTimeout(timer);timer=setTimeout(function(){st.q=el.q.value;st.axis='';visible=12;save();renderRail();renderList();},140);});
el.origin.innerHTML='<option value="">'+esc(t('catAllOrigins'))+'</option><option value="TW">'+esc(t('catTaiwan'))+'</option><option value="CN">'+esc(t('catChina'))+'</option>';el.origin.value=st.origin;el.origin.addEventListener('change',function(){st.origin=el.origin.value;visible=12;save();renderRail();renderList();});
el.list.addEventListener('keydown',function(e){if((e.key==='Enter'||e.key===' ')&&e.target.classList.contains('cat-row')){e.preventDefault();openProduct(e.target.dataset.id);}});
el.list.addEventListener('click',function(e){var b=e.target.closest('[data-add]');if(b){add(b.dataset.add);return;}var row=e.target.closest('[data-id]');if(row)openProduct(row.dataset.id);});
el.detail.addEventListener('click',function(e){var b=e.target.closest('[data-add]');if(b)add(b.dataset.add);});
el.detail.addEventListener('change',function(e){if(e.target.id==='cat-size'){sizeChoice[st.pick]=e.target.value;syncSelection();}});
el['enq-list'].addEventListener('click',function(e){var b=e.target.closest('[data-drop]');if(b){var index=st.enq.indexOf(b.dataset.drop);st.enq=st.enq.filter(function(k){return k!==b.dataset.drop;});delete quantities[b.dataset.drop];save();syncSelection();renderEnq();var buttons=el['enq-list'].querySelectorAll('[data-drop]'),target=buttons[Math.min(index,buttons.length-1)]||el.notes;target.focus({preventScroll:true});}});
el['enq-list'].addEventListener('input',function(e){if(e.target.dataset.qty){var n=Number(e.target.value);quantities[e.target.dataset.qty]=Number.isInteger(n)&&n>0&&n<=10000000?n:'';}});
el.notes.addEventListener('input',function(){notes=el.notes.value;});
el['enq-open'].addEventListener('click',function(){if(productDialog&&productDialog.open)productDialog.close();var d=dialog('enquiry');d.appendChild(el.enq);d.showModal();});
el['enq-copy'].addEventListener('click',copy);el['enq-clear'].addEventListener('click',function(){st.enq=[];quantities={};notes='';el.notes.value='';save();syncSelection();renderEnq();el.notes.focus({preventScroll:true});});
document.getElementById('cat-more').addEventListener('click',function(){var firstNew=visible;visible+=12;renderList();var row=el.list.children[firstNew];if(row)row.focus({preventScroll:true});});
renderAll();
function enquiryLink(){if(location.hash==='#enquiry')el['enq-open'].click();}enquiryLink();window.addEventListener('hashchange',enquiryLink);
})();
