(function(){/* CostNow workspace extras: lane rate, scenario A, quote sheet */
var host=document.getElementById('p-landed2');if(!host)return;
var $=function(id){return document.getElementById(id);};
var D={};try{D=JSON.parse(document.getElementById('outlook-data').textContent)||{};}catch(e){}
var fmt=function(x){return 'US$'+Math.round(x).toLocaleString('en-US');};
/* 1 · today's lane rate under the freight input */
(function(){var el=$('ws_frt_live'),co=$('bc_co'),frt=$('bc_frt');if(!el||!co||!frt)return;
 var lanes=(D.shipping&&D.shipping.lanes)||[];
 var WANT={us:'N. America',ca:'N. America',de:'N. Europe',nl:'N. Europe',fr:'N. Europe',pl:'N. Europe',uk:'N. Europe',es:'Mediterranean',au:'Australia',nz:'Australia',jp:'Japan'};
 function lane(){var w=WANT[co.value];if(!w)return null;for(var i=0;i<lanes.length;i++){if(String(lanes[i].lane||'').indexOf(w)>=0)return lanes[i];}return null;}
 function paint(){var l=lane();if(!l||!l.rate){el.hidden=true;el.textContent='';return;}
  el.hidden=false;
  el.innerHTML='Today '+l.lane+': US$'+Number(l.rate).toLocaleString('en-US')+'/FEU'+(l.transit?' · '+l.transit:'')+' <button type="button" class="ws-use">Use ×1 FEU</button>';
  el.querySelector('.ws-use').addEventListener('click',function(){frt.value=l.rate;frt.dispatchEvent(new Event('input',{bubbles:true}));});}
 co.addEventListener('change',function(){setTimeout(paint,0);});paint();})();
/* 2 · scenario A: pin the current shipment, read deltas as you retune */
(function(){var btn=$('ws_pinA'),out=$('ws_dA');if(!btn||!out)return;
 var A=null;try{A=JSON.parse(localStorage.getItem('bd_ws_A'));}catch(e){}
 function d(x,ref){var v=x-ref,a=Math.abs(v);if(a<0.005)return null;return (v>0?'+':'\u2212')+'US$'+(a>=100?Math.round(a).toLocaleString('en-US'):a.toFixed(2));}
 function paint(){if(!A||!window.__ws){out.textContent='';return;}
  var bits=[],u=d(window.__ws.per,A.per),t=d(window.__ws.total,A.total);
  if(u)bits.push('unit '+u);if(t)bits.push('total '+t);
  if(window.__wsMg&&A.retail!=null){var r=d(window.__wsMg.retail,A.retail);if(r)bits.push('retail '+r);}
  out.textContent=bits.length?('\u0394 vs A: '+bits.join(' \u00b7 ')):'\u0394 vs A: unchanged';}
 function label(){btn.textContent=A?'Scenario A pinned \u00b7 clear':'Pin as scenario A';btn.classList.toggle('on',!!A);}
 btn.addEventListener('click',function(){
  if(A){A=null;try{localStorage.removeItem('bd_ws_A');}catch(e){}}
  else if(window.__ws){A={per:window.__ws.per,total:window.__ws.total,retail:window.__wsMg?window.__wsMg.retail:null};try{localStorage.setItem('bd_ws_A',JSON.stringify(A));}catch(e){}}
  label();paint();});
 document.addEventListener('ws:landed',paint);label();paint();})();
/* 3 · numbered quote sheet through the browser's print-to-PDF */
(function(){var btn=$('ws_sheet_btn');if(!btn)return;
 btn.addEventListener('click',function(){
  var no;try{no=(parseInt(localStorage.getItem('bd_ws_qn')||'0',10)+1);localStorage.setItem('bd_ws_qn',String(no));}catch(e){no=1;}
  var ref='CN-'+new Date().getFullYear()+'-'+String(no).padStart(4,'0');
  var co=$('bc_co'),dest=co&&co.options[co.selectedIndex]?co.options[co.selectedIndex].textContent:'\u2014';
  var rows=function(id){var e=$(id);return e?e.innerHTML:'';};
  var ins=[['Destination',dest]];
  [['FOB value','bc_fob','USD'],['Quantity','bc_qty','pcs'],['Ocean freight','bc_frt','USD'],['Insurance rate','bc_ins','%'],['Duty','bc_duty','%'],['Import tax / VAT','bc_tax','%'],['Brokerage','bc_brk','USD'],['Inland delivery','bc_inl','USD'],['Other','bc_oth','USD'],['Target margin','ws_mg','%']].forEach(function(x){var e=$(x[1]);if(e)ins.push([x[0],Number(e.value).toLocaleString('en-US')+' '+x[2]]);});
  var sheet=$('ws-sheet');if(!sheet){sheet=document.createElement('div');sheet.id='ws-sheet';document.body.appendChild(sheet);}
  sheet.innerHTML='<div class="qs-head"><b>BIRDLAND \u00b7 COSTNOW</b><span>Cost estimate '+ref+' \u00b7 '+new Date().toISOString().slice(0,10)+'</span></div>'
   +'<h4>Shipment</h4>'+ins.map(function(x){return '<div class="bcrow"><span>'+x[0]+'</span><b>'+x[1]+'</b></div>';}).join('')
   +'<h4>Landed outcome</h4>'+rows('bc_out')
   +'<h4>Retail outcome</h4>'+rows('ws_mg_out')
   +'<h4>Origin compare \u00b7 Taiwan vs China</h4>'+rows('ws_duty_out')
   +'<p class="qs-note">Indicative planning figures generated by Birdland CostNow from public daily data \u2014 not a quotation, '+(window.BL_ADVICE||'not legal, customs or trade advice.')+' birdland.com.tw</p>';
  document.body.classList.add('ws-printing');
  var done=function(){document.body.classList.remove('ws-printing');window.removeEventListener('afterprint',done);};
  window.addEventListener('afterprint',done);setTimeout(done,4000);
  window.print();});})();
})();