module.exports = {
  routes: {
    "Blade & spring steel": { pop: 5, cost: 3, note: "Core material for every cutting edge; mid-range cost" },
    "Stainless steel": { pop: 3, cost: 4, note: "Premium rust-resistant blades and trowels; pricier than carbon steel" },
    "Aluminium": { pop: 3, cost: 3, note: "Lightweight shafts and heads on premium lines; moderate cost" },
    "Rigid plastics": { pop: 5, cost: 1, note: "Dominant for handles and housings; cheapest structural material" },
    "Grip compounds": { pop: 5, cost: 2, note: "Soft overmould grip now a standard ergonomic selling point" },
    "Timber": { pop: 2, cost: 3, note: "Heritage handle material for spades and forks; pricier than plastic" },
    "Fabric": { pop: 2, cost: 1, note: "Gloves and straps only; low cost, limited to few SKUs" },

    "Stamping": { pop: 5, cost: 1, note: "the default for volume blades and brackets" },
    "Hot forging": { pop: 2, cost: 4, note: "Heavier tool heads; costlier and less common in mass DIY" },
    "Cold forging": { pop: 2, cost: 3, note: "Higher-strength small parts like pivot pins; moderate extra cost" },
    "Laser cutting": { pop: 2, cost: 4, note: "Short runs or premium blade profiles; costly per part" },
    "Tube drawing": { pop: 3, cost: 3, note: "Shafts for forks, spades, loppers; moderate cost, fairly common" },
    "Tube bending": { pop: 3, cost: 2, note: "Bends stock tube into handles and frames; cheaper than drawing" },
    "Swaging": { pop: 2, cost: 2, note: "Tapers or joins tube ends; niche, low-cost forming step" },
    "Wood turning": { pop: 2, cost: 3, note: "Turned wooden handles for heritage lines; pricier than moulding" },
    "Injection moulding": { pop: 5, cost: 2, note: "Dominant process for plastic handles and housings; low unit cost" },
    "Two-shot over-moulding": { pop: 4, cost: 4, note: "Common for soft-grip handles; pricier tooling than single-shot moulding" },
    "Dip moulding": { pop: 3, cost: 2, note: "Dips tool ends for handle coatings; simple, fairly cheap process" },

    "Through hardening": { pop: 3, cost: 2, note: "Hardens solid steel parts like trowel blades; simple, low cost" },
    "Quench & temper": { pop: 4, cost: 2, note: "Standard treatment for spring steel blades and springs; low cost" },
    "Induction (local) hardening": { pop: 3, cost: 3, note: "Hardens only the cutting edge; needs dedicated equipment, moderate cost" },
    "Solution annealing": { pop: 1, cost: 3, note: "Stainless-specific heat treatment; rare outside premium stainless tool lines" },
    "Stress relief": { pop: 2, cost: 1, note: "Reduces warping after forming; cheap, occasional extra process step" },
    "Hardness banding by grade": { pop: 2, cost: 1, note: "Sorts output into hardness grades; cheap QC step, not universal" },

    "Progressive dies": { pop: 4, cost: 4, note: "High-volume stamping tooling; expensive investment, common for big brands" },
    "Single-station dies": { pop: 3, cost: 2, note: "Simple tooling for low-volume stampings; cheaper than progressive dies" },
    "Trim & pierce tools": { pop: 3, cost: 2, note: "Secondary stamping operations; moderate tooling cost, fairly common" },
    "Injection moulds": { pop: 5, cost: 5, note: "Needed for every plastic part; the most expensive tooling category" },
    "Welding jigs": { pop: 2, cost: 1, note: "Simple fixtures for welded assemblies; cheap, used only occasionally" },
    "Assembly fixtures": { pop: 3, cost: 1, note: "Keeps assembly consistent across lines; low individual tooling cost" },
    "Gauges": { pop: 3, cost: 1, note: "Inspection tooling for dimensions; cheap, moderately common across lines" },

    "Riveting": { pop: 5, cost: 1, note: "Standard pivot joint for shears and secateurs; cheap and common" },
    "Bolted joints": { pop: 3, cost: 2, note: "Adjustable pivots or handle attachment; costs more than riveting" },
    "Snap-fit": { pop: 4, cost: 1, note: "Plastic housings clip together; cheap, very common on mass tools" },
    "Press-fit": { pop: 3, cost: 1, note: "Ferrule onto handle or blade tang; cheap, common assembly method" },
    "Spot welding": { pop: 2, cost: 2, note: "Joins metal frame assemblies; moderate cost, less used on hand tools" },
    "MIG welding": { pop: 2, cost: 3, note: "Welds heavier long-handled tool assemblies; costlier than spot welding" },
    "Brazing": { pop: 1, cost: 4, note: "Premium blade-to-tang joints; rare and costly in mass-market channel" },
    "Over-moulded joints": { pop: 4, cost: 3, note: "Bonds soft grip onto handle body; common on ergonomic mid-tier lines" },
    "Adhesive bonding": { pop: 3, cost: 2, note: "Glues ferrules and labels; moderate cost, fairly common assembly step" },

    "Zinc plating": { pop: 5, cost: 1, note: "Default cheap rust protection for small steel parts and blades" },
    "Nickel-chrome plating": { pop: 2, cost: 4, note: "Decorative premium finish; pricier, used mainly on higher-end lines" },
    "Dacromet": { pop: 1, cost: 4, note: "Specialist corrosion coating; rare in consumer garden tools, costly" },
    "Powder coating": { pop: 4, cost: 2, note: "Durable colour finish on metal heads; moderate cost, fairly common" },
    "Wet paint": { pop: 3, cost: 1, note: "Cheap colour coat on lower-cost ranges; less durable than powder" },
    "E-coat": { pop: 1, cost: 3, note: "Electro-deposited priming; rare for hand tools, more of an automotive process" },
    "Anodising": { pop: 2, cost: 3, note: "Colours and protects aluminium parts; pricier than plain paint" },
    "Polishing": { pop: 3, cost: 2, note: "Bright blade finish for shelf appeal; moderate labour cost" },
    "Sand-blasting": { pop: 2, cost: 1, note: "Surface prep before coating; cheap step, not used on every SKU" },
    "Lacquer or oil on wood": { pop: 2, cost: 1, note: "Finish for timber handles only; cheap, relevant to wood SKUs" },
    "Heat transfer print": { pop: 3, cost: 1, note: "Cheap branding and graphics onto plastic handles; fairly common" },
    "Laser marking": { pop: 3, cost: 2, note: "Permanent blade branding; moderate cost, common on premium tool lines" },

    "Hardness sampling": { pop: 3, cost: 1, note: "Batch check of blade hardness; low-cost routine sampling step" },
    "Open/close cycle life": { pop: 2, cost: 2, note: "Durability test for shears and loppers pivots; moderate extra cost" },
    "Salt-spray hours": { pop: 2, cost: 2, note: "Corrosion test for plated parts; moderate cost, not every SKU" },
    "Dimensional AQL": { pop: 4, cost: 1, note: "Standard incoming and outgoing dimension check; cheap and common" },
    "Edge & function check": { pop: 5, cost: 1, note: "Near-universal sharpness and function check before packing; low cost" },
    "Joint pull test": { pop: 2, cost: 2, note: "Destructive test on riveted or bolted joints; occasional, moderate cost" },
    "Pack drop test": { pop: 3, cost: 1, note: "Standard transit test for retail packaging; cheap and common" },
    "Barcode & label check": { pop: 5, cost: 1, note: "Mandatory retailer compliance scan; cheap, done on every unit" }
  },
  materials: {
    "Blade and spring steel": { pop: 5, cost: 3, note: "Core material for every cutting edge; mid-range cost" },
    "Stainless steel": { pop: 3, cost: 4, note: "Premium rust-resistant blades and trowels; pricier than carbon steel" },
    "Plating and coating": { pop: 5, cost: 2, note: "Near-universal rust protection on steel parts; low added cost" },
    "Aluminium": { pop: 3, cost: 3, note: "Lightweight shafts and heads on premium lines; moderate cost" },
    "Rigid plastics": { pop: 5, cost: 1, note: "Dominant for handles and housings; cheapest structural material" },
    "Grips and soft compounds": { pop: 5, cost: 2, note: "Soft overmould grip now a standard ergonomic selling point" },
    "Timber": { pop: 2, cost: 3, note: "Heritage handle material for spades and forks; pricier than plastic" },
    "Fabric and textile": { pop: 2, cost: 1, note: "Gloves and straps only; low cost, limited to few SKUs" },
    "Packaging board": { pop: 5, cost: 1, note: "Universal for cartons and header cards; cheapest packaging material" }
  },
  packs: {
    "Corrugated export carton": { pop: 5, cost: 2, note: "Standard bulk shipping carton used for nearly every export run" },
    "Colour box": { pop: 4, cost: 4, note: "Printed retail box for premium SKUs; pricier than plain carton" },
    "Hang tag / header card": { pop: 5, cost: 1, note: "Cheap card for blister and peg-hook display; near-universal" },
    "Blister pack": { pop: 4, cost: 3, note: "Plastic-and-card display pack for small tools; under regulatory pressure" },
    "Skin pack": { pop: 2, cost: 3, note: "Film-wrapped display for irregular shapes; less common than blister" },
    "Paper-and-plastic composite": { pop: 3, cost: 2, note: "Hybrid format cutting plastic content; growing under packaging regulation" },
    "Shrink film": { pop: 3, cost: 1, note: "Cheap overwrap for bundling multipacks; fairly common, low cost" },
    "Label set": { pop: 5, cost: 1, note: "Barcode and care labels; cheap, applied to almost every unit" },
    "Void fill": { pop: 3, cost: 1, note: "Paper or foam fill for protection; cheap, used selectively" },
    "Strapping": { pop: 2, cost: 1, note: "Secures bundled units or pallets; cheap, used only occasionally" },
    "Pallet": { pop: 5, cost: 5, note: "Base unit for bulk transport; highest per-unit cost in group" }
  }
};
